### PR TITLE
Create license.txt

### PR DESCRIPTION
**Pull request by hearbenji**

### CODE REVIEW

**Comment by hhirsch** [comment]
@hearbenji There already is a license for you in a imho more appropriate place. Look at this: https://github.com/GlPortal/glportal_raw_data/blob/master/audio/music/benji/LICENCE.md

**Comment by hhirsch** [comment]
@hearbenji Agree?

**Comment by hearbenji** [comment]
Absolutely agreed. This is mostly me just trying to figure out git. It's a little pathetic, I know. Thanks for your patience. I'm going to get some help this week.

Benji

**Comment by hhirsch** [comment]
@hearbenji No problem. Git is very forgiving of mistakes and I have no problem with the extra work.

**Pull request closed without merging**
